"""Added vnc_port column to Server model

Revision ID: 8aa6224c3bed
Revises: ee2f25c9cdad
Create Date: 2024-05-01 17:29:53.432187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa6224c3bed'
down_revision: Union[str, None] = 'ee2f25c9cdad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('vnc_port', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_server_vnc_port'), 'server', ['vnc_port'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_vnc_port'), table_name='server')
    op.drop_column('server', 'vnc_port')
    # ### end Alembic commands ###
