"""updated server

Revision ID: f2bcab0841a1
Revises: 7160b92cd06a
Create Date: 2024-04-23 03:46:40.372534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bcab0841a1'
down_revision: Union[str, None] = '7160b92cd06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('node_id', sa.Integer(), nullable=True))
    op.alter_column('server', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'server', 'node', ['node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'server', type_='foreignkey')
    op.alter_column('server', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('server', 'node_id')
    # ### end Alembic commands ###
