"""update ActiveServer

Revision ID: f07bb4e7a073
Revises: c83b4250b4a6
Create Date: 2024-02-05 11:41:41.818631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07bb4e7a073'
down_revision: Union[str, None] = 'c83b4250b4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_server', sa.Column('xml', sa.Text(), nullable=True))
    op.drop_index('ix_active_server_iso', table_name='active_server')
    op.create_unique_constraint(None, 'active_server', ['xml'])
    op.drop_column('active_server', 'iso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_server', sa.Column('iso', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'active_server', type_='unique')
    op.create_index('ix_active_server_iso', 'active_server', ['iso'], unique=False)
    op.drop_column('active_server', 'xml')
    # ### end Alembic commands ###
