"""Updated Server model

Revision ID: aecad71b3567
Revises: 8aa6224c3bed
Create Date: 2024-05-16 13:28:46.333383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecad71b3567'
down_revision: Union[str, None] = '8aa6224c3bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_server_ipv4', table_name='server')
    op.create_index(op.f('ix_server_ipv4'), 'server', ['ipv4'], unique=False)
    op.drop_index('ix_server_ipv6', table_name='server')
    op.create_index(op.f('ix_server_ipv6'), 'server', ['ipv6'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_ipv6'), table_name='server')
    op.create_index('ix_server_ipv6', 'server', ['ipv6'], unique=True)
    op.drop_index(op.f('ix_server_ipv4'), table_name='server')
    op.create_index('ix_server_ipv4', 'server', ['ipv4'], unique=True)
    # ### end Alembic commands ###
