"""init payment

Revision ID: 86789287d7ed
Revises: d0ef4a2892a2
Create Date: 2024-03-03 19:02:05.961818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86789287d7ed'
down_revision: Union[str, None] = 'd0ef4a2892a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    op.create_index(op.f('ix_discount_user_id'), 'discount', ['user_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('active_server_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['active_server_id'], ['active_server.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_active'), 'payment', ['active'], unique=False)
    op.create_index(op.f('ix_payment_active_server_id'), 'payment', ['active_server_id'], unique=False)
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_index(op.f('ix_payment_server_id'), 'payment', ['server_id'], unique=False)
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.add_column('ipv4', sa.Column('available', sa.Boolean(), nullable=False))
    op.drop_column('ipv4', 'avaible')
    op.add_column('ipv6', sa.Column('available', sa.Boolean(), nullable=False))
    op.drop_column('ipv6', 'avaible')
    op.add_column('server', sa.Column('available', sa.Boolean(), nullable=False))
    op.drop_column('server', 'avaible')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('avaible', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('server', 'available')
    op.add_column('ipv6', sa.Column('avaible', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('ipv6', 'available')
    op.add_column('ipv4', sa.Column('avaible', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('ipv4', 'available')
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_server_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_active_server_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_active'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_discount_user_id'), table_name='discount')
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_table('discount')
    # ### end Alembic commands ###
