"""added user settings and discounts

Revision ID: c83b4250b4a6
Revises: 
Create Date: 2024-01-30 18:16:31.658307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83b4250b4a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=False),
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('disk', sa.Integer(), nullable=False),
    sa.Column('traffic', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('avaible', sa.Boolean(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_id'), 'server', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('active_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('iso', sa.String(), nullable=True),
    sa.Column('ipv4', sa.String(), nullable=False),
    sa.Column('ipv6', sa.String(), nullable=True),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_server_id'), 'active_server', ['id'], unique=False)
    op.create_index(op.f('ix_active_server_ipv4'), 'active_server', ['ipv4'], unique=True)
    op.create_index(op.f('ix_active_server_ipv6'), 'active_server', ['ipv6'], unique=True)
    op.create_index(op.f('ix_active_server_iso'), 'active_server', ['iso'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.CheckConstraint('discount >= 0 AND id <= 30', name='check_discount_range'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_discount'), 'discount', ['discount'], unique=False)
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.Column('reset_password', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_notifications'), 'user_settings', ['notifications'], unique=True)
    op.create_index(op.f('ix_user_settings_reset_password'), 'user_settings', ['reset_password'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_reset_password'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_notifications'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_index(op.f('ix_discount_discount'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_active_server_iso'), table_name='active_server')
    op.drop_index(op.f('ix_active_server_ipv6'), table_name='active_server')
    op.drop_index(op.f('ix_active_server_ipv4'), table_name='active_server')
    op.drop_index(op.f('ix_active_server_id'), table_name='active_server')
    op.drop_table('active_server')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_server_id'), table_name='server')
    op.drop_table('server')
    # ### end Alembic commands ###
