"""added payment

Revision ID: f05a3336e071
Revises: f07bb4e7a073
Create Date: 2024-02-26 15:52:28.987565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05a3336e071'
down_revision: Union[str, None] = 'f07bb4e7a073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipv4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('avaible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipv4_id'), 'ipv4', ['id'], unique=False)
    op.create_index(op.f('ix_ipv4_ip'), 'ipv4', ['ip'], unique=True)
    op.create_table('ipv6',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('avaible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipv6_id'), 'ipv6', ['id'], unique=False)
    op.create_index(op.f('ix_ipv6_ip'), 'ipv6', ['ip'], unique=True)
    op.create_table('server_ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_ip_id'), 'server_ip', ['id'], unique=False)
    op.create_index(op.f('ix_server_ip_ip'), 'server_ip', ['ip'], unique=True)
    op.drop_index('ix_discount_discount', table_name='discount')
    op.drop_index('ix_discount_id', table_name='discount')
    op.drop_table('discount')
    op.add_column('server', sa.Column('disk_type', sa.String(), nullable=False))
    op.add_column('server', sa.Column('disk_size', sa.Integer(), nullable=False))
    op.drop_column('server', 'disk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('disk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('server', 'disk_size')
    op.drop_column('server', 'disk_type')
    op.create_table('discount',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('discount >= 0 AND id <= 30', name='check_discount_range'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='discount_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='discount_pkey')
    )
    op.create_index('ix_discount_id', 'discount', ['id'], unique=False)
    op.create_index('ix_discount_discount', 'discount', ['discount'], unique=False)
    op.drop_index(op.f('ix_server_ip_ip'), table_name='server_ip')
    op.drop_index(op.f('ix_server_ip_id'), table_name='server_ip')
    op.drop_table('server_ip')
    op.drop_index(op.f('ix_ipv6_ip'), table_name='ipv6')
    op.drop_index(op.f('ix_ipv6_id'), table_name='ipv6')
    op.drop_table('ipv6')
    op.drop_index(op.f('ix_ipv4_ip'), table_name='ipv4')
    op.drop_index(op.f('ix_ipv4_id'), table_name='ipv4')
    op.drop_table('ipv4')
    # ### end Alembic commands ###
