"""delete payment

Revision ID: fbbdef9b35d7
Revises: ff4eb92d9c82
Create Date: 2024-03-30 23:22:52.230684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbdef9b35d7'
down_revision: Union[str, None] = 'ff4eb92d9c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_active', table_name='payment')
    op.drop_index('ix_payment_id', table_name='payment')
    op.drop_index('ix_payment_payment_uri', table_name='payment')
    op.drop_index('ix_payment_server_id', table_name='payment')
    op.drop_index('ix_payment_user_id', table_name='payment')
    op.drop_table('payment')
    op.drop_index('ix_discount_id', table_name='discount')
    op.drop_index('ix_discount_user_id', table_name='discount')
    op.drop_table('discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='discount_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='discount_pkey')
    )
    op.create_index('ix_discount_user_id', 'discount', ['user_id'], unique=False)
    op.create_index('ix_discount_id', 'discount', ['id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], name='payment_server_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='payment_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_pkey')
    )
    op.create_index('ix_payment_user_id', 'payment', ['user_id'], unique=False)
    op.create_index('ix_payment_server_id', 'payment', ['server_id'], unique=False)
    op.create_index('ix_payment_payment_uri', 'payment', ['payment_uri'], unique=False)
    op.create_index('ix_payment_id', 'payment', ['id'], unique=False)
    op.create_index('ix_payment_active', 'payment', ['active'], unique=False)
    # ### end Alembic commands ###
