"""updated server model

Revision ID: 010417ebb896
Revises: f2bcab0841a1
Create Date: 2024-04-23 13:29:38.314604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010417ebb896'
down_revision: Union[str, None] = 'f2bcab0841a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
