"""update active server

Revision ID: 3032c7ac4405
Revises: 86789287d7ed
Create Date: 2024-03-06 20:06:59.312377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3032c7ac4405'
down_revision: Union[str, None] = '86789287d7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_server', sa.Column('active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_active_server_active'), 'active_server', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_active_server_active'), table_name='active_server')
    op.drop_column('active_server', 'active')
    # ### end Alembic commands ###
