"""added node

Revision ID: 03840f0c6787
Revises: fbbdef9b35d7
Create Date: 2024-04-23 02:33:38.621019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03840f0c6787'
down_revision: Union[str, None] = 'fbbdef9b35d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=False),
    sa.Column('cores_available', sa.Integer(), nullable=False),
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('ram_available', sa.Integer(), nullable=False),
    sa.Column('disk_type', sa.String(), nullable=False),
    sa.Column('disk_size', sa.Integer(), nullable=False),
    sa.Column('disk_size_available', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_id'), 'node', ['id'], unique=False)
    op.create_index(op.f('ix_node_ip'), 'node', ['ip'], unique=True)
    op.drop_index('ix_server_ip_ip', table_name='server_ip')
    op.drop_table('server_ip')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_ip',
    sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ip', name='server_ip_pkey')
    )
    op.create_index('ix_server_ip_ip', 'server_ip', ['ip'], unique=True)
    op.drop_index(op.f('ix_node_ip'), table_name='node')
    op.drop_index(op.f('ix_node_id'), table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###
