"""updated node

Revision ID: 7160b92cd06a
Revises: 03840f0c6787
Create Date: 2024-04-23 02:40:02.871852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7160b92cd06a'
down_revision: Union[str, None] = '03840f0c6787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'location')
    # ### end Alembic commands ###
