name: Run tests

on:
  push:
    branches:
      - master

jobs:
  tests_python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        apt install -y gcc make automake autoconf fakeroot libvirt
        pip install ".[dev]"

    - name: Test with pytest
      run: pytest
