name: Run tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        options: >-
          -e POSTGRES_PASSWORD=postgres
          -e POSTGRES_DB=postgres
          -p 5432:5432
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        sudo apt install -y gcc make automake autoconf fakeroot libvirt-dev postgresql-client
        pip install ".[dev]"
    - name: Create user and database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "CREATE USER underground WITH PASSWORD 'underground';"
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "CREATE DATABASE underground;"
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "ALTER USER underground CREATEDB;"
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "ALTER DATABASE underground OWNER TO underground;"
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE underground TO underground;"
    - name: Run migrations
      run: alembic upgrade head
    - name: Test with pytest
      run: pytest
      env:
        TESTING: true
